### ISSUE TITLE
how to set xlim / ylim for plot_quantum()

### ISSUE THREAD

**Issue by MCarreroPazos** [r-spatialecology/onpoint#12]
Is there any way to adjust the limits for x and y axis? I couldn't find any options inside plot_quantum() and with using e.g. xlim=c(0,300), ylim=c(0, 10) as arguments does not work.

**Comment by mhesselbarth** [comment]
Hey, 

Thanks for the issue and sorry for the late reply. I was on holidays last week but will look into this next week and come back to you!

**Comment by mhesselbarth** [comment]
Since the returning object is a ggplot you should be able to do `plot_quantums(csr_envelope, ylab = "g(r)") + scale_y_continuous(limits = c(0, 10))`.

If you install the latest version from Github, you can now also specify the min/max y values of the quantum bar to control both position and size using e.g. `quantum_position = c(-1, 0)`

**Comment by mhesselbarth** [comment]
Please re-open if required. Will close for now
